POST http://localhost:3001/api/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "name": "Test",
    "sur_name": "Testovich",
    "login": "Neo123",
    "email": "test@example38.com",
    "password": "Iuserala87$lla"
}